---
title: Characterization of Harmonic Emission of Individual Wind Turbines and PV Inverters Based on Measurements - Part 1 - Photovoltaic Inverters
author:
- Florian Ackermann
- Hasanali Moghadam
- Jan Meyer
- Sascha Mueller
- Max Domagk
- Fritz Santjer
- Issam Athamna
- Rainer Klosse
date: '2016-11-01'
description: 6th Solar Integration Workshop
categories:
- Conference paper
doi: 10.24406/publica-fhg-408356
tags:
- Harmonics
- Modeling
- Background Distortion
- Network Harmonic Impedance
- Inverter
---

**Abstract:** The harmonic emission of wind turbines and PV inverters is usually determined by field measurements. Consequently it is influenced by several external factors like supply voltage, the network impedeance or the point of operation. Within the framework of the research project "NetzHarmonie", which is funded by the German government, new methods to evaluate harmonic emission in the grid are explored. This paper is the first part of a publication presenting measurement results from field tests and test benches. This paper paper focuses on tests that were performed in order to analyze the response of PV inverters for specific external factors.

**Keywords:** Harmonics, Modeling, Background Distortion, Network Harmonic Impedance, Inverter

[DOI](https://doi.org/10.24406/publica-fhg-408356){.btn .btn-outline-primary .btn-sm}
