---
title: Seasonal Variations in Long-Term Measurements of Power Quality Parameters
author:
- Max Domagk
- Jan Meyer
- Peter Schegner
date: '2015-06-01'
description: 2015 IEEE Eindhoven PowerTech
categories:
- Conference paper
doi: 10.1109/PTC.2015.7232396
tags:
- Power Quality
- Data Mining
- Harmonics
- Time Series Analysis
- Consumer Behavior
---

**Abstract:** Power quality levels in public low voltage grids are influenced by many factors which can either be assigned to the electrical environment (connected consumers, connected generation, network characteristics) or to the non-electrical environment (e.g. climatic conditions) at the measurement site. Type and amount of connected consumers (consumer topology) are expected to have a very high impact on power quality (PQ) levels. The usage behaviour of equipment by customers usually varies over the year. Subsequently the levels of PQ parameters like harmonics may show a seasonal variation. The aim of the paper is the identification and quantification of these seasonal variations. It starts with a systematic overview of major factors impacting Power Quality levels and continues with the classification of the typical types of their variation (short-term, medium-term and long-term). Next a two-stage approach based on time series decomposition is introduced in order to quantify seasonal variations by a set of indices. Finally several existing long-term measurements of public LV grids lasting more than one year are selected for a comprehensive illustration of the method. The sites represent different consumer topologies, like shops, offices and residential areas. Seasonal variations are quantified in detail for these sites and selected current quality parameters.

**Keywords:** Power Quality, Data Mining, Harmonics, Time Series Analysis, Consumer Behavior

[DOI](https://doi.org/10.1109/PTC.2015.7232396){.btn .btn-outline-primary .btn-sm}
