project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "research/**/*.qmd"
    - "publications/**/*.qmd"
    - "presentations/**/*.qmd"
  resources:
    - "files/"
    - "fonts/"

website:
  title: "Max Domagk"
  description: "Power quality, data mining and electrical power systems research at TUD Dresden University of Technology."
  site-url: https://maxdomagk.de
  favicon: images/icon.png
  open-graph: true
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: presentations/index.qmd
        text: Presentations
  search: false
  page-footer:
    left: "&copy; 2026 Max Domagk"
    right:
      - href: impressum.qmd
        text: Impressum
      - href: privacy.qmd
        text: Privacy

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css
    toc: false
    anchor-sections: false
    link-external-newwindow: true
