---
title: Survey of Harmonic Voltage and Current Unbalance in the German Transmission System based on Field Measurements considering Measurement Uncertainty
author:
- Olga Zyabkina
- Max Domagk
- Ana Maria Blanco
- Jan Meyer
- Marco Lindner
date: '2025-09-15'
description: NEIS 2025; Conference on Sustainable Energy Supply and Energy Storage Systems
categories:
- Conference paper
doi: 10.30420/566633030
tags:
- Measurements
- Unbalance
- Harmonics
- Power Quality
---

**Abstract:** The increasing integration of power electronic installations into transmission systems has amplified the need for accurate harmonic studies. Recently, especially the consideration of unbalance in harmonic studies attracted increasing attention. Field measurements are often an essential prerequisite for these studies, e.g. for harmonic model parameterization or validation of simulation results. However, the use of field measurements requires that the measured harmonic phasors meet a certain accuracy and that the aggregated phase angles for a specific aggregation interval (e.g. 10 minutes) are meaningful. Therefore, the first part of the paper discusses those measurement challenges and provides recommendations to address them by applying the concepts of uncertainty thresholds and prevailing ratio. Using the guidance of part one, the second part of the paper evaluates the harmonic unbalance for eight sites in a part of the German transmission system based on 10-minute aggregated voltage and current harmonic phasors. For a better interpretation of harmonic unbalance, the Relative Unbalance Level is introduced. Results reveal significant unbalance across all analysed harmonic orders. These findings challenge the assumption of balanced harmonic conditions and support the need to consider unbalance for harmonic studies in transmission systems.

**Keywords:** Measurements, Unbalance, Harmonics, Power Quality

[DOI](https://doi.org/10.30420/566633030){.btn .btn-outline-primary .btn-sm}
