---
title: Modelling the Propagation of Harmonic Voltages in Large Medium Voltage Distribution Networks
author:
- Adnan Bosovic
- Mustafa Music
- Herwig Renner
- Andreas Abart
- Ewald Traxler
- Jan Meyer
- Max Domagk
date: '2019-06-01'
description: 25th International Conference on Electricity Distribution (CIRED)
categories:
- Conference paper
doi: 10.34890/46
---

**Abstract:** Harmonic voltages are important power quality (PQ) parameters, mainly caused by non-linear loads that act as harmonic current sources in the network. Modelling the propagation of harmonic voltages in large medium voltage (MV) distribution networks has so far been a challenge, mainly due to huge number of different harmonic sources that have an influence on harmonic voltage distortion in the network. This research uses a methodology of aggregate harmonic source modelling of major customer categories in MV distribution networks, based on several measurements and knowledge from the literature. This paper presents the results of propagation of 5th and 7th harmonic voltages in one large real MV distribution network. The simulations are performed using professional software tool, and two commonly used methods for modelling harmonic sources are applied. The results of harmonic voltage propagation from simulations show a very good match compared to the results from PQ measurement instruments installed in the analysed network. It is shown that the correct propagation of harmonic voltages can be achieved using models, even in large real MV distribution networks. The methodology used is relatively simple, with limited number of measurements needed to develop a model. Therefore, it can easily be applied to other MV networks. The results of this research will be used as an input for a PQ monitoring placement algorithm.

[DOI](https://doi.org/10.34890/46){.btn .btn-outline-primary .btn-sm}
