---
title: Deterministic Aggregated Harmonic Source Models for Harmonic Analysis of Large Medium Voltage Distribution Networks
author:
- Adnan Bosovic
- Herwig Renner
- Andreas Abart
- Ewald Traxler
- Jan Meyer
- Max Domagk
- Mustafa Music
date: '2019-08-01'
description: IET Generation, Transmission & Distribution
categories:
- Journal article
doi: 10.1049/iet-gtd.2018.7120
---

**Abstract:** Modelling of harmonics in large medium voltage (MV) distribution networks has so far been a challenge due to the presence of a large number of harmonic sources contributing to total harmonic voltages. This study proposes a deterministic methodology of modelling harmonics in large real MV distribution networks using aggregate harmonic source models parameterised based on measurements and results from the literature. In this research, background harmonic voltages from the sub-transmission system are parameterised based on measurements in the analysed network. Aggregate harmonic current emission of different customer categories in low-voltage (LV) networks (households and small commercial customers) parameterised based on several measurements in LV networks was dominated by residential or office customer type configurations. The harmonic current emission of industrial customers is parameterised based on the results from published literature. Two methods for modelling harmonic sources are used and compared: (i) modelling according to the IEC 61000-3-6 summation law and recommended summation exponents and (ii) modelling using complex phasors. The results of the models show a good match with the measurements from power quality monitors installed in the analysed MV network. Based on these results, the method according to the IEC 61000-3-6 is recommended for large MV distribution networks.

[DOI](https://doi.org/10.1049/iet-gtd.2018.7120){.btn .btn-outline-primary .btn-sm}
