---
title: Trend Identification in Power Quality Measurements
author:
- Max Domagk
- Olga Zyabkina
- Jan Meyer
- Peter Schegner
date: '2015-09-01'
description: 2015 Australasian Universities Power Engineering Conference (AUPEC)
categories:
- Conference paper
doi: 10.1109/AUPEC.2015.7324851
tags:
- Power Quality
- Data Mining
- Harmonics
- Time Series Analysis
- Trend Analysis
---

**Abstract:** Power quality (PQ) levels in public low voltage grids are influenced by many factors like type of connected customers, level of distributed generation or climatic conditions. In particular, type and number of the connected electronic equipment have a significant impact on PQ levels. Therefore, the introduction of new device technologies on a large scale, like the transition from incandescent to LED lamps, might result in long-term changes to the levels of PQ parameters (e.g. harmonics). Major aims of the paper are the identification and quantification of long-term trends in time series of continuous PQ parameters which can support network operators with the early detection of fundamental changes in PQ levels. This information can e.g. support the asset management or network planning in managing PQ levels using optimized costs. The paper begins with a systematic overview of major factors with impact on PQ levels and continues with a classification of their typical variation behavior (short-term, medium-term and long-term). The analysis of the long-term behavior (trend) starts with the extraction of a smoothed trend component based on time series decomposition. This trend component is used to quantify global trends (looking on the measurement duration as a whole) and local trends (looking on individual segments of the whole time series). Finally, the application of both methods is illustrated for selected voltage and current quality parameters using a set of three year measurements from German LV grids with different consumer configuration.

**Keywords:** Power Quality, Data Mining, Harmonics, Time Series Analysis, Trend Analysis

[DOI](https://doi.org/10.1109/AUPEC.2015.7324851){.btn .btn-outline-primary .btn-sm}
