---
title: New Evaluation Methods for Harmonic Emission of Renewable Generation
author:
- Issam Athamna
- Marko Muehlberg
- Fritz Santjer
- Kaveh Malekian
- Marc Florian Meyer
- Hendrik Vennegerts
- Jan Meyer
- Max Domagk
- Florian Ackermann
- Rainer Klosse
- Karsten Kuech
date: '2016-11-15'
description: 15th Wind Integration Workshop
categories:
- Conference paper
url: https://windintegrationworkshop.org/proceedings/
tags:
- Harmonics
- Modeling
- Measurement
- Evaluation
- Active Harmonic Compensation
---

**Abstract:** With the increase of renewable energy resources, the share of power electronic increases in the public grid. These power electronics produce harmonic currents and inject them into the grid. This causes distortion of voltage, which has significant influence on the power quality in the grid. Existing standards define harmonic current emission limits, which might be unnecessarily strict and consequently do not effectively utilize the hosting capacity of the grid in terms of harmonics. Within the framework of the research project "NetzHarmonie", which is funded by the German government, new methods to evaluate harmonic emission in the grid are explored.

**Keywords:** Harmonics, Modeling, Measurement, Evaluation, Active Harmonic Compensation

[Link](https://windintegrationworkshop.org/proceedings/){.btn .btn-outline-primary .btn-sm}
