---
title: Integration of Clustering Techniques in Probabilistic Current and Voltage Harmonic Forecasting
author:
- Antonio Bracale
- Pierluigi Caramia
- Pasquale De Falco
- Max Domagk
- Jan Meyer
date: '2025-09-26'
description: IEEE Transactions on Power Delivery
categories:
- Journal article
doi: 10.1109/TPWRD.2025.3614751
tags:
- Power Quality
- Harmonic Distortion
- Time Series Analysis
- Probabilistic Forecasting
- Clustering
---

**Abstract:** Forecasts of waveform harmonic distortions can be used by operators to implement corrective actions for complying with suggested limits, to refine the components' dynamic rating predictions, and to run scheduling strategies for controllable resources in smart/micro grids. Nevertheless, developing a unified forecasting methodology for all the harmonic components is challenged by their different time-varying characteristics. To tackle this problem, this paper proposes to integrate clustering techniques in probabilistic current and voltage harmonic forecasting methodologies. Identifying common characteristics in the harmonic component patterns enables building the underlying forecasting models in a diversified manner, with a model for each cluster. Since true memberships of unobserved patterns to clusters are unknown to the forecaster, the individual forecasts must be optimally recombined to get the final predictions. This paper proposes the combination through an optimized Beta-transformed Linear Pool (BLP), mitigating the lack of calibration that can occur when combining probabilistic forecasts. To assess the clustering effectiveness, parametric and nonparametric underlying forecasting models are considered, and different combination benchmarks are taken as reference. Applications based on actual measurements in commercial, office, or residential sites confirm the suitability of the proposal, with relative improvements of the forecast accuracy over persistence benchmarks from 2 to 48%.

**Keywords:** Power Quality, Harmonic Distortion, Time Series Analysis, Probabilistic Forecasting, Clustering

[DOI](https://doi.org/10.1109/TPWRD.2025.3614751){.btn .btn-outline-primary .btn-sm}
