---
title: Automated Test System for Accuracy Verification of Power Quality Measurement Instruments
author:
- Jan Meyer
- Peter Schegner
- Max Domagk
- Reinhard Kuntner
- Franz Hillenbrand
date: '2009-06-01'
description: 20th International Conference and Exhibition on Electricity Distribution (CIRED 2009)
categories:
- Conference paper
doi: 10.1049/cp.2009.0913
---

**Abstract:** In the last years voltage quality in the supply networks becomes more and more important for the distribution network operators (DNO). Moreover the interest of the European regulatory authorities (CEER) in voltage quality increases constantly over the last years. Due to the mentioned facts the number of power quality measurement campaigns and consequently the number of permanently installed power quality measurement instruments is growing continuously. To ensure the necessary accuracy of the measurement instruments, periodic accuracy verification is required. If the verification fails, the measurement instrument must be re-calibrated. Usually for both verification and calibration the measurement instrument must be send to the manufacturer. Especially in the case of a great number of permanently installed measurement instruments this is time- and cost-intensive and causes unwanted interruptions of the power quality measurements for several days or weeks. Maybe for this reason in many cases a measurement instrument is calibrated only sporadic or not at all. The paper describes an automated test system for accuracy verification of a specific power quality measurement instrument according to parts of EN 61000-4-30. The tests run automatically and are designed to be carried out "in the field" without dismounting the measurement instrument. In the actual stage the project was realized as "proof of concept" in co-operation with a test equipment manufacturer and a measurement instrument manufacturer.

[DOI](https://doi.org/10.1049/cp.2009.0913){.btn .btn-outline-primary .btn-sm}
