---
title: Benchmark Low Voltage Distribution Networks Based on Cluster Analysis of Actual Grid Properties
author:
- Joerg Dickert
- Max Domagk
- Peter Schegner
date: '2013-06-01'
description: 2013 IEEE Grenoble Conference
categories:
- Conference paper
doi: 10.1109/PTC.2013.6652250
tags:
- Clustering Methods
- Data Handling
- Power System Planning
- Multivariate Methods
---

**Abstract:** Distribution systems are supplying many customers with electricity requiring a high number of equipment and lines. It is tedious to analyze all low-voltage (LV) networks of a distribution system operator (DSO). Because of the large number of LV-networks within the system benchmark networks are required. For bulk analysis the networks have to represent a large number of networks within the system. For extreme value analysis the most critical networks have to be identified and examined. Benchmark networks representing typical LV-networks for bulk analysis can be derived from technical data of these networks using multivariate methods. This paper describes the data allocation and application of cluster analysis for this purpose. The presented benchmark networks are based on German conditions. The networks are also reviewed under the aspect of feasibility. The benchmark networks are characterized by their supply obligation as well as the network data and properties are given for benchmark analysis. The paper also includes the diverse experience in data allocation, analysis of the data and gives assistants for prospective data allocation combined with cluster analysis of LV-networks. With the information given in the paper also benchmark networks adapted to a variety of other applications can be derived.

**Keywords:** Clustering Methods, Data Handling, Power System Planning, Multivariate Methods

[DOI](https://doi.org/10.1109/PTC.2013.6652250){.btn .btn-outline-primary .btn-sm}
